ibtracs.last3years:
    paths:
      raw: data/raw/ibtracs.last3years.csv
      processed: data/processed/ibtracs.last3years/
    target: LANDFALL
    target_transform: binary_landfall
    preprocessing:
      missing_values: median
      encoding: onehot
    features:
      datetime:
        - ISO_TIME
      drop:
        - WMO_AGENCY
        - WMO_PRES
        - WMO_WIND
        - USA_R50_NE
        - USA_R50_NW
        - USA_R50_SE
        - USA_R50_SW
        - CMA_PRES
        - CMA_LON
        - CMA_LAT
        - CMA_WIND
        - CMA_CAT
        - TOKYO_R50_DIR
        - TOKYO_R30_DIR
        - TOKYO_LON
        - TOKYO_LAT
        - TOKYO_PRES
        - USA_SEAHGT
        - USA_SEARAD_NE
        - USA_SEARAD_NW
        - USA_SEARAD_SE
        - USA_R64_NE
        - HKO_LON
        - HKO_LAT
        - HKO_CAT
        - USA_R64_SE
        - USA_R64_NW
        - HKO_WIND
        - HKO_PRES
        - USA_R64_SW
        - KMA_LAT
        - KMA_LON
        - KMA_CAT
        - KMA_WIND
        - KMA_PRES
        - USA_SEARAD_SW
        - BOM_TYPE
        - BOM_PRES
        - BOM_WIND
        - BOM_LAT
        - BOM_LON
        - USA_GUST
        - BOM_POCI
        - BOM_ROCI
        - TOKYO_WIND
        - TOKYO_R30_SHORT
        - TOKYO_R30_LONG
        - KMA_R30_DIR
        - KMA_R30_SHORT
        - KMA_R30_LONG
        - TOKYO_LAND
        - BOM_GUST
        - BOM_GUST_PER
        - KMA_R50_DIR
        - KMA_R50_SHORT
        - KMA_R50_LONG
        - BOM_PRES_METHOD
        - TOKYO_R50_SHORT
        - TOKYO_R50_LONG
        - REUNION_LAT
        - REUNION_LON
        - REUNION_TYPE
        - REUNION_WIND
        - BOM_R34_SW
        - BOM_CI
        - BOM_TNUM
        - REUNION_PRES
        - BOM_R34_NW
        - BOM_R34_SE
        - NEWDELHI_DP
        - NEWDELHI_LAT
        - NEWDELHI_LON
        - NEWDELHI_GRADE
        - NEWDELHI_WIND
        - NEWDELHI_PRES
        - BOM_R34_NE
        - BOM_POS_METHOD
        - BOM_RMW
        - NEWDELHI_CI
        - REUNION_TNUM
        - REUNION_GUST_PER
        - BOM_R50_SW
        - USA_EYE
        - REUNION_R34_NW
        - REUNION_R34_SW
        - REUNION_R34_SE
        - REUNION_R34_NE
        - BOM_R50_SE
        - BOM_R50_NW
        - BOM_R50_NE
        - NADI_LON
        - NADI_LAT
        - NADI_WIND
        - NADI_CAT
        - NADI_PRES
        - WELLINGTON_LAT
        - WELLINGTON_LON
        - REUNION_CI
        - WELLINGTON_WIND
        - REUNION_RMW
        - REUNION_R50_NW
        - REUNION_R50_SW
        - REUNION_R50_SE
        - REUNION_R50_NE
        - BOM_R64_SE
        - BOM_R64_NE
        - BOM_R64_SW
        - BOM_R64_NW
        - WELLINGTON_PRES
        - BOM_EYE
        - USA_RECORD
        - MLC_WIND
        - MLC_LAT
        - MLC_LON
        - MLC_CLASS
        - REUNION_R64_NE
        - REUNION_R64_NW
        - REUNION_R64_SW
        - REUNION_GUST
        - REUNION_R64_SE
        - NEUMANN_PRES
        - MLC_PRES
        - NEUMANN_WIND
        - NEWDELHI_POCI
        - NEUMANN_LON
        - DS824_LAT
        - DS824_LON
        - DS824_STAGE
        - DS824_WIND
        - DS824_PRES
        - TD9636_LAT
        - TD9636_LON
        - TD9636_STAGE
        - TD9636_WIND
        - TD9636_PRES
        - TD9635_LAT
        - TD9635_LON
        - TD9635_WIND
        - TD9635_PRES
        - NEUMANN_LAT
        - NEUMANN_CLASS
        - TD9635_ROCI
