ibtracs.last3years:
  paths:
    raw: data/raw/ibtracs.last3years.csv
    processed: data/processed/ibtracs.last3years/
  target: LANDFALL
  target_transform: binary_landfall
  preprocessing:
    missing_values: median
    encoding: onehot
  features:
    datetime:
      - ISO_TIME

ibtracs.ALL.list.v04r01:
  paths:
    raw: data/raw/ibtracs.ALL.list.v04r01.csv
    processed: data/processed/ibtracs.ALL.list.v04r01/
  target: LANDFALL
  target_transform: binary_landfall
  preprocessing:
    missing_values: median
    encoding: onehot
  features:
    datetime:
      - ISO_TIME